version: "3"

networks:
  devnet:
    driver: bridge

services:
 nexus:
  image: sonatype/nexus3
  container_name: nexus3
  ports:
    - "8081:8081"
  networks:
    - devnet
  volumes:
    - "/opt/nexus/:/var/lib/nexus"

